# Generated by Django 5.1.7 on 2025-04-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='csv_upload',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='plot_type',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='y_axis',
        ),
        migrations.AddField(
            model_name='analysis',
            name='author_name',
            field=models.CharField(default='Unknown Author', max_length=255),
        ),
        migrations.AddField(
            model_name='analysis',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='plots',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='title',
            field=models.CharField(default='Untitled Analysis', max_length=255),
        ),
    ]
